language: java
jdk:
  - oraclejdk8 
  - oraclejdk7
  - openjdk7
env:
  - PLAY_VERSION=master PLAY_PATH=play1-master PLAY_NEED_BUILD=true PLAY_DOWNLOAD=https://github.com/playframework/play1/archive/master.zip
  - PLAY_VERSION=old_master PLAY_PATH=play1-old_master PLAY_NEED_BUILD=true PLAY_DOWNLOAD=https://github.com/playframework/play1/archive/old_master.zip
  - PLAY_VERSION=1.4.x PLAY_PATH=play1-1.4.x PLAY_NEED_BUILD=true PLAY_DOWNLOAD=https://github.com/playframework/play1/archive/1.4.x.zip 
before_script:
  - wget ${PLAY_DOWNLOAD}
  - unzip -q ${PLAY_VERSION}.zip
  - if [[ "${PLAY_NEED_BUILD}" == "true" ]]; then ant -buildfile "./${PLAY_PATH}/framework/build.xml"; fi
  
script: 
  - ant test -Dplay.path=${PLAY_PATH}
after_failure: 
    cat ./samples-and-tests/just-test-cases/test-result/*.failed.html
notifications:
  email:
    on_success: change
    on_failure: always